// NPC dialogue engine. With ANTHROPIC_API_KEY set, responses are generated by
// Claude using the persona + injected memory. Without a key, a deterministic
// offline persona engine produces in-character lines that still react to the
// memory object, so the full loop demos with zero credentials.
import Anthropic from "@anthropic-ai/sdk";
import { buildSystemPrompt, NPCS } from "./npcs.js";

const MODEL = process.env.ENGRAM_MODEL || "claude-sonnet-4-6";
const apiKey = process.env.ANTHROPIC_API_KEY;
const client = apiKey ? new Anthropic({ apiKey }) : null;

export function aiInfo() {
  return { engine: client ? `claude:${MODEL}` : "offline-mock", model: MODEL };
}

function clampDelta(n, lo = -20, hi = 20) {
  const x = Math.round(Number(n) || 0);
  return Math.max(lo, Math.min(hi, x));
}

// Normalise whatever the model returns into the shape the server relies on.
function normalise(raw, npc) {
  const out = raw && typeof raw === "object" ? raw : {};
  const update = out.memory_update && typeof out.memory_update === "object" ? out.memory_update : {};
  let options = Array.isArray(out.options) ? out.options.filter((o) => typeof o === "string") : [];
  options = options.slice(0, 4);
  if (options.length < 3) {
    options = [...options, "Tell me more.", "I should go.", "What do you make of me?"].slice(0, 3);
  }
  return {
    dialogue: typeof out.dialogue === "string" && out.dialogue.trim()
      ? out.dialogue.trim()
      : `${npc.name} regards you in silence.`,
    options,
    memory_update: {
      trust_delta: clampDelta(update.trust_delta),
      emotional_state:
        typeof update.emotional_state === "string" && update.emotional_state.trim()
          ? update.emotional_state.trim().toLowerCase()
          : undefined,
      debts_delta: clampDelta(update.debts_delta, -999, 999),
      summary:
        typeof update.summary === "string" && update.summary.trim()
          ? update.summary.trim()
          : "Spoke with the traveller.",
    },
  };
}

export async function generateTurn({ npcId, memory, walletShort, playerLine, crossMemory }) {
  const npc = NPCS[npcId];
  if (!npc) throw new Error(`Unknown NPC: ${npcId}`);

  if (!client) {
    return mockTurn({ npc, memory, playerLine, crossMemory });
  }

  const system = buildSystemPrompt(npc, memory, walletShort, crossMemory);
  const userContent = playerLine
    ? `The player says/does: "${playerLine}"`
    : `The player has just approached you. Greet them.`;

  const resp = await client.messages.create({
    model: MODEL,
    max_tokens: 600,
    system,
    messages: [{ role: "user", content: userContent }],
  });

  const text = resp.content
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("");

  let parsed;
  try {
    parsed = JSON.parse(extractJson(text));
  } catch {
    parsed = { dialogue: text };
  }
  return normalise(parsed, npc);
}

function extractJson(text) {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1) return text;
  return text.slice(start, end + 1);
}

// ─── Offline persona engine ───────────────────────────────────────────────────
// Reacts to trust + player intent so the memory loop is fully demonstrable
// without an API key. Keyword-driven, deliberately simple, in character.
function mockTurn({ npc, memory, playerLine, crossMemory }) {
  const t = memory.trust_level;
  const seen = memory.interaction_history.length;
  const line = (playerLine || "").toLowerCase();
  const tone = t >= 70 ? "warm" : t >= 40 ? "wary" : "cold";

  const intent = classify(line);
  let trust_delta = 0;
  let debts_delta = 0;
  let dialogue = "";
  let emotional_state = memory.emotional_state;

  const greet =
    seen === 0
      ? "A new face in Aldenmoor."
      : tone === "warm"
      ? "Ah, you again — good."
      : tone === "cold"
      ? "You. I remember you."
      : "Back again, are you.";

  if (npc.id === "aldric") {
    if (intent === "pay") { trust_delta = 8; debts_delta = -Math.min(memory.debts, 5); emotional_state = "pleased"; dialogue = `${greet} Coin up front — that's how I like it. For you, a fair price.`; }
    else if (intent === "haggle") { trust_delta = -6; emotional_state = "annoyed"; dialogue = `${greet} Haggling again? My prices are my prices. ${memory.debts > 0 ? `And you still owe me ${memory.debts}.` : ""}`; }
    else if (intent === "threat") { trust_delta = -12; emotional_state = "guarded"; dialogue = `${greet} Threaten me in my own stall? The guard knows your face, friend.`; }
    else if (intent === "buy") { trust_delta = t >= 70 ? 4 : 1; debts_delta = 3; emotional_state = "businesslike"; dialogue = `${greet} ${t >= 70 ? "For a loyal customer, a small discount." : "That'll be on credit, then — mind you settle up."}`; }
    else { dialogue = `${greet} ${memory.debts > 0 ? `You owe me ${memory.debts}, by the way.` : "Looking to trade?"}`; }
  } else if (npc.id === "maren") {
    if (intent === "brave") { trust_delta = 10; emotional_state = "respectful"; dialogue = `${greet} You stood your ground. The guard remembers courage.`; }
    else if (intent === "coward") { trust_delta = -10; emotional_state = "disappointed"; dialogue = `${greet} You ran. I will not warn cowards when the next danger comes.`; }
    else if (intent === "threat") { trust_delta = -8; emotional_state = "stern"; dialogue = `${greet} Mind your tongue. I've put down worse than you.`; }
    else if (intent === "help") { trust_delta = 6; emotional_state = "approving"; dialogue = `${greet} Protecting the weak. That's the measure of a person.`; }
    else { dialogue = `${greet} ${t >= 70 ? "Stay sharp — there's trouble on the east road. I tell you because you've earned it." : t < 40 ? "I'm watching how you carry yourself." : "Keep your blade clean and your conscience cleaner."}`; }
  } else { // sable
    const intel = crossMemory
      ? Object.entries(crossMemory)
          .map(([n, m]) => `${n} has you at ${m.trust_level}`)
          .join(", ")
      : "";
    if (intent === "bribe") { trust_delta = 5; emotional_state = "amused"; dialogue = `${greet} Coin? Now you speak my language. ${intel ? `For instance — ${intel}. Worth knowing, no?` : "Ask, and I'll whisper."}`; }
    else if (intent === "threat") { trust_delta = -7; emotional_state = "cool"; dialogue = `${greet} Careful. I know things about you the others don't. ${intel}.`; }
    else { dialogue = `${greet} The town talks, you know. ${intel ? `${intel}.` : "And I listen to all of it."} ${t < 40 ? "Some of what I've heard, you wouldn't like sold." : "Stay on my good side and it stays with me."}`; }
  }

  const options = optionsFor(npc.id);
  const summary = summaryFor(npc.id, intent);
  return {
    dialogue,
    options,
    memory_update: { trust_delta: clampDelta(trust_delta), emotional_state, debts_delta, summary },
  };
}

function classify(line) {
  if (/\b(pay|repay|settle|here'?s the coin|i'?ll pay)\b/.test(line)) return "pay";
  if (/\b(haggle|cheaper|discount|too much|lower the price)\b/.test(line)) return "haggle";
  if (/\b(buy|purchase|i'?ll take|sell me)\b/.test(line)) return "buy";
  if (/\b(threaten|kill|hurt|or else|rob)\b/.test(line)) return "threat";
  if (/\b(stand|fight|brave|defend|charge|face it)\b/.test(line)) return "brave";
  if (/\b(run|flee|hide|coward|retreat|abandon)\b/.test(line)) return "coward";
  if (/\b(help|protect|save|shield|rescue)\b/.test(line)) return "help";
  if (/\b(bribe|coin for|pay you|gold for info|here'?s gold)\b/.test(line)) return "bribe";
  return "talk";
}

function optionsFor(id) {
  if (id === "aldric") return ["Here's the coin I owe you.", "Can't you lower the price?", "I'll take it on credit.", "What's new in stock?"];
  if (id === "maren") return ["I stood and fought.", "I ran — I won't lie.", "I helped defend the village.", "What dangers should I know of?"];
  return ["Here's gold — what do you know?", "What have the others said about me?", "I have nothing for you today.", "Don't test me, broker."];
}

function summaryFor(id, intent) {
  const map = {
    pay: "Settled a debt with coin.",
    haggle: "Tried to haggle the price down.",
    buy: "Bought goods, partly on credit.",
    threat: "Made a threat.",
    brave: "Stood and fought instead of fleeing.",
    coward: "Fled from danger.",
    help: "Helped protect others.",
    bribe: "Paid for information.",
    talk: "Made small talk.",
  };
  return map[intent] || "Spoke with the traveller.";
}
